version: "3.9"
services:

  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  express-db-server:
    build: ./backend
    container_name: my-express-server
    ports:
      - 3001:3001
    depends_on:
      - postgres
  sql-loader:
    build: ./db/db-scripts
    container_name: my-sql-loader
    depends_on:
      - postgres

  react:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    container_name: my-favourite-react-app
    ports:
      - 3000:3000
    volumes:
     - /app/node_modules
     - ./frontend:/App
    depends_on:
      - postgres
    #  - express-db-server